#!/bin/sh

if [ $# -ne 2 ]; then
    echo "usage: check <expression> <expected-result>" >&2
    exit 2
fi

expression=$1
expected=$2

superc "$expression" >expression.s 2>superc.out
if [ $? -ne 0 ]; then
    echo "expression '$expression' failed with:"
    cat superc.out
    if [ "`<superc.out`" != "$expected" ]; then
        echo "EXPECTED $expected"
        exit 1
    fi
    exit 0
fi
#cat expression.s
gcc expression.s main.o -o expression
if [ $? -ne 0 ]; then
    exit 1
fi
./expression >expression.out 2>&1
echo -n "$expression => "
cat expression.out
if [ "`<expression.out`" != "$expected" ]; then
    echo "EXPECTED $expected"
    exit 1
fi
